name: clang-format

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

addons:
  apt:
    packages:
      - clang-format

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run clang-format
      run: ${{github.workspace}}/clang-format

