name: clang-tidy

on:
  pull_request:
    branches: [ "master" ]

jobs:
  clang-tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies for build
        run: sudo apt install meson libpcap-dev libcppunit-dev
      - name: Configure Meson for minimal build
        run: meson setup ${{github.workspace}}/build .
      - name: clang-tidy-diff
        run: git diff master | clang-tidy-diff -p1 -path build/ -export-fixes build/fixes.yml
      - name: check result
        run: exit `stat -c %s fixes.yml`
