name: cpp-linter

on:
  workflow_dispatch:
    #  pull_request:
    #    branches: [ "master" ]

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies for build
        run: sudo apt install meson libpcap-dev libcppunit-dev
      - name: Configure Meson for minimal build
        run: meson setup ${{github.workspace}}/build .
      - name: Massage compile_commands.json so that the action works 1/2
        run: sed -i 's/\/build//g' ${{github.workspace}}/build/compile_commands.json
      - name: Massage compile_commands.json so that the action works 1/2
        run: sed -i 's/\.\.\///g' ${{github.workspace}}/build/compile_commands.json
      - name: C/C++ Linter
        uses: cpp-linter/cpp-linter-action@main
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          database: ${{github.workspace}}/build
          tidy-checks: ''
          version: 14
          thread-comments: true

      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        # run: echo "Some files failed the linting checks!"
        # for actual deployment
        run: exit 1
